[build]
  command = "pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.10"

# Handle all requests through the API function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Custom domain configuration
[context.production.environment]
  BASE_URL = "https://cv-ats.netlify.app" 