[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && cd frontend && npm install && npm run build"

[deploy]
startCommand = "PYTHONPATH=$PYTHONPATH:. uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[deploy.files]
frontend = "frontend/build"

[deploy.env]
PYTHONPATH = "." 